name: GCE Connect And Execute Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: github-actions-test	  
  GCE_INSTANCE_ZONE: asia-northeast3-a	
  
jobs:
  setup-pull-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Show Pwd
        run: pwd
        
      - name: Show file list
        run: ls -al
    
      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Connect GCE And execute docker ps
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'github-actions-test'
          zone: 'asia-northeast3-a'
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: "./deploy.sh"

      # Example of using the output
      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
